export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 14,
      category: 'mobiles',
      title: "Apple iPhone 15 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 15 Pro (258GB) - White',
      price: '99999',
    },
    {
      id: 15,
      category: 'mobiles',
      title: "Apple iPhone 15 Pro Max",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 15 Pro Max (1TB) - Black',
      price: '109999',
    },
    {
      id: 13,
      category: 'mobiles',
      title: "Apple iPhone 10",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 10(128GB) - Plum',
      price: '49999',
    },
   
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 16,
      category: 'tablets',
      title: "Apple iPad (10th Generation)",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'A14 Bionic chip, 27.69 cm (10.9″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera, Touch ID, All-Day Battery Life-Silver',
      price: '36900',
    },
    {
      id: 17,
      category: 'tablets',
      title: "Apple iPad (10th Generation,with AI Assistance)",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'A14 Bionic chip, 27.69 cm (10.9″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera, Touch ID, All-Day Battery Life-Silver',
      price: '46900',
    },
    {
      id: 18,
      category: 'tablets',
      title: "Apple iPad Pro 11″ (4th Generation)",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'M2 chip, Liquid Retina Display, 128GB, Wi-Fi 6E, 12MP front/12MP and 10MP Back Cameras, Face ID, All-Day Battery Life – Space Grey',
      price: '73900',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 10,
      category: 'laptops',
      title: "Apple MacBook Air Pro Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 15.3-inch/33.74 cm Retina Display, ',
      price: '88999',
    },

    {
      id: 11,
      category: 'laptops',
      title: "Zenbook Pro 16X OLED (UX7602)",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Innovative ASUS Supernova SoM Design, 16.33-inch/35.74 cm Retina Display, ',
      price: '68999',
    },
    {
      id: 12,
      category: 'laptops',
      title: "Inspiron Laptops & 2-in-1 PCs",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'AMD Ryzen™ 5 7530U 6-core/12-thread Processor with Radeon, 18.33-inch/35.74 cm Amoled Display, ',
      price: '58999',
    },
    

  ]